### ISSUE TITLE
What did you change?

### ISSUE THREAD

**Issue by E3V3A** [ggeorgovassilis/circuitjs1#6]
Hi George!

I see you did quite a lot of changes ~March last year.  But I don't see any PR's in the original repos.
What exactly did you change? What/Why?
(unfortunately your commit messages are not telling much...)

Thanks in advance.

**Comment by ggeorgovassilis** [comment]
I submitted a PR for mavenisation which wasn't accepted. This fork ports
the build to maven. There's also a branch where I started separating logic
from view to make it unit testable.

**Comment by E3V3A** [comment]
Hi,
What a shame. CI would definitely be a useful improvement. 
I also noticed there was a more recent PR for Mavenization that also got rejected. 
So I was mainly wondering about the other branch you mentioned.

**Comment by ggeorgovassilis** [comment]
The author has a particular, practical, mindset which makes collaboration on anything that isn't customisation of existing functionality difficult. The separation task is hard because the view API deeply woven into the rest of the logic.
________________________________
